### ISSUE TITLE
DOWNLOADS THE FILE...

### ISSUE THREAD

**Issue by notseenee** [notseenee/hscpastpapers#6]
Submitter: Anonymouza
On Chrome (windows), I clicked SDD > HSC Exam Paper, it downloaded: "software-design+-dev-hsc-exam-2012" (no file format) onto my system instead of displaying it!

ALSO - Feature Idea:
--> When I switch between sample answers/the paper please make it RETAIN the position I was in so I don't have to scroll all the way back to the question (save it in a variable and call the pdf reader to do it, if it's possible perhaps?)

Overall, it works really well so good job!!

**Comment by notseenee** [comment]
The SDD 2012 HSC exam paper should download with a .pdf file extension now so it should be viewable when downloaded - still working on a fix to get it to view the pdf file and not download it

**Comment by featherbear** [comment]
Yo! 
For the feature idea, might as well have a split screen mode
The answer page could blur or dim when the mouse isn't hovering over to help with the 'out of sight'-ness

**Comment by notseenee** [comment]
* Update on the SDD 2012 HSC paper - unfortunately this is an issue with the NESA website where the file is listed without the `.pdf` extension so their server sends it with the MIME type `octet-stream` rather than `application/pdf`, so the browser will automatically download the file
    * A possible solution is to use `pdf.js` but it needs a CORS proxy since the PDF is being loaded cross-origin from NESA's site and there is no viable way to do this - using a free CORS proxy service like [crossorigin.me](https://crossorigin.me) would kill performance and they don't recommend using it for live websites

* Split view has been implemented (dad7f14), but the dimming function was not, though you can just exit split view and open it again and it will not reset, so it basically has the same effect as dimming/hiding the document

* Retaining the position of the PDF is not possible with how the web app is built - right now it uses `iframe`s that point to a URL on NESA's website, which triggers the browser's PDF plugin to display the PDF. For security purposes, browsers block JavaScript from accessing the contents of a cross-domain `iframe`, i.e. the `iframe` must show a webpage with the url `https://hscpastpapers.com/*` for its contents to be accessible
    * A solution to this is to use `object`s, which directly call the browser's PDF plugin, but using `iframe`s are better because
      - if the URL is wrong (e.g. 404) it will show the default browser error and
      - if NESA's server sends the file as an `octet-stream`, it will automatically download. An `object` would just display nothing
